enabled_locales: ["en", "ja", "vi"]
client:
  host: "localhost:3000"
time_zone: +7
valid_email_regex: !ruby/regexp '/\A[\w+-.]+@[a-z\d-]+(.[a-z\d-]+)*.[a-z]+\z/i'
username_max_length: 50
email_max_length: 255
password_min_length: 6
